---
name: OneTimeCodeAuthentication
After:
  - "#coresecurity"
---
SilverStripe\Security\Member:
  extensions:
    - Sunnysideup\OneTimeCode\MemberExtension

SilverStripe\Security\Security:
  extensions:
    - Sunnysideup\OneTimeCode\ControllerExtension

SilverStripe\Core\Injector\Injector:
  SilverStripe\Security\Security:
    properties:
      Authenticators:
        onetimecode: '%$Sunnysideup\OneTimeCode\OneTimeCodeAuthenticator'
