SilverStripe\Security\Member:
  extensions:
    - Sunnysideup\OneTimeCode\MemberExtension

SilverStripe\CMS\Controllers\ContentController:
  extensions:
    - Sunnysideup\OneTimeCode\ControllerExtension

SilverStripe\Core\Injector\Injector:
  SilverStripe\Security\Security:
    properties:
      Authenticators:
        pincode: '%$Sunnysideup\OneTimeCode\PincodeAuthenticator'